### ISSUE TITLE
ship a signed binary for macos?

### ISSUE THREAD

**Issue by devoncarew** [dart-lang/tflite_native#41]
Extracted out from a comment here: https://github.com/dart-lang/tflite_native/pull/37#issuecomment-555787915.

Locally I saw failures running the tests (on macos), which seemed to imply that we should be shipping signed .so binaries on the mac.

```
Invalid argument(s): Failed to load dynamic library (dlopen(/Users/devoncarew/projects/dart-lang/tflite_native/lib/src/blobs/libtensorflowlite_c-mac64.so, 1): no suitable image found.  Did find:
  	/Users/devoncarew/projects/dart-lang/tflite_native/lib/src/blobs/libtensorflowlite_c-mac64.so: code signature in (/Users/devoncarew/projects/dart-lang/tflite_native/lib/src/blobs/libtensorflowlite_c-mac64.so) not valid for use in process using Library Validation: mapped file has no cdhash, completely unsigned? Code has to be at least ad-hoc signed.)
```

@lambdabaa, @sjindel-google, @mkustermann, @dcharkes - do you have a sense for whether signing the native libraries (at least on a mac) is or will soon be necessary?

**Comment by dcharkes** [comment]
It's probable that signing will be necessary in the next version of MacOS. In the latest version of MacOS signing dynamic libraries is necessary if the executable is signed. See the discussion on https://github.com/dart-lang/sdk/issues/38314.

**Comment by devoncarew** [comment]
I think that means that signed libraries are now necessary, given that the SDK is itself signed.

**Comment by dcharkes** [comment]
Correct.

**Comment by devoncarew** [comment]
It looks like the .so file checked in here can only be run from a non-signed version of the Dart SDK (one built locally on a developer's machine).

This .so file, when included in the Dart SDK, is signed as part of the Dart SDK signing process, so users won't see this issue in dev and stable builds of the Dart SDK.

**Comment by devoncarew** [comment]
I'm not sure where that leaves us in terms of running the tests on the CI however.

**Comment by mkustermann** [comment]
> I'm not sure where that leaves us in terms of running the tests on the CI however.

Depending on how your CI is setup, you might be able to use our unsigned SDK for it. All our released SDKs are available in unsigned form (and signed  for MacOS):
```
% gsutil ls gs://dart-archive/channels/dev/raw/2.7.0-dev.1.0/sdk/   
gs://dart-archive/channels/dev/raw/2.7.0-dev.1.0/sdk/dartsdk-linux-arm-release.zip
gs://dart-archive/channels/dev/raw/2.7.0-dev.1.0/sdk/dartsdk-linux-arm64-release.zip
gs://dart-archive/channels/dev/raw/2.7.0-dev.1.0/sdk/dartsdk-linux-ia32-release.zip
gs://dart-archive/channels/dev/raw/2.7.0-dev.1.0/sdk/dartsdk-linux-x64-release.zip
gs://dart-archive/channels/dev/raw/2.7.0-dev.1.0/sdk/dartsdk-macos-ia32-release.zip
gs://dart-archive/channels/dev/raw/2.7.0-dev.1.0/sdk/dartsdk-macos-x64-release.zip
gs://dart-archive/channels/dev/raw/2.7.0-dev.1.0/sdk/dartsdk-windows-ia32-release.zip
gs://dart-archive/channels/dev/raw/2.7.0-dev.1.0/sdk/dartsdk-windows-x64-release.zip
...

% gsutil ls gs://dart-archive/channels/dev/signed/2.7.0-dev.1.0/sdk/
gs://dart-archive/channels/dev/signed/2.7.0-dev.1.0/sdk/dartsdk-macos-x64-release.zip
```

Those are downloadable via the `http://storage.googleapis.com/dart-archive/...` URL.

/cc @athomas
